export const userTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  VALIDATE_BOOKING: "VALIDATE_BOOKING",
  CANCEL_VALIDATE_BOOKING: "CANCEL_VALIDATE_BOOKING",
  ADD_BOOKING: "ADD_BOOKING",
  REMOVE_BOOKING: "REMOVE_BOOKING",
  RESET_BOOKING: "RESET_BOOKING"
};
